# fly.toml app configuration file generated for mosq on 2023-05-31T22:57:12-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mosq"
primary_region = "gdl"

[http_service]
  internal_port = 1883
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
